apiVersion: "fortinet.com/v1"
kind: Fortigate
metadata:
  name: fgt-az
spec:
  fgt-name: fgt-az
  fgt-ip: 172.27.44.126
  vdom: "root"
scope: Cluster
#will use controller-image: param modified by the controller use as name if not set by CRD
# modify with controller
#  state: "up"
#  license-expiration: "date"