kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fortigate-ctrl
rules:
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - "customresourcedefinitions"
  verbs:
  - "get"
  - "delete"
  - "watch"
  - "list"
  - "update"
  - "patch"
  - "create"
- apiGroups: [""]
  resources:
  - "pods"
  - "endpoints"
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services", "services/status"]
  verbs: ["get", "watch", "list", "update", "patch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - "fortinet.com"
  resources:
  - "fortigates"
  - "fortigates/status"
  verbs:
  - "*"
- apiGroups:
  - "fortigates.fortinet.com"
  resources:
  - "lb-fgts"
  - "lb-fgts/status"
  verbs:
  - "*"
