apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fortigates.fortinet.com
spec:
  group: fortinet.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: fortigates
    singular: fortigate
    kind: Fortigate
    shortNames:
     - fgt
  additionalPrinterColumns:
  - JSONPath: .status.status
    name: status
    type: string
  - JSONPath: .spec.fgt-publicip
    name: externalip
    type: string
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lb-fgts.fortigates.fortinet.com
spec:
  group: fortigates.fortinet.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: lb-fgts
    singular: lb-fgt
    kind: LoadBalancerFortigate
    shortNames:
     - lb-fgt
  additionalPrinterColumns:
  - JSONPath: .status.status
    name: status
    type: string
  - JSONPath: .spec.fgt
    name: fortigate
    type: string
  subresources:
    status: {}