kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fortigate-ctrl-rolebinding
subjects:
- kind: ServiceAccount
  name: fortigate-ctrl
  namespace: fortinet
roleRef:
  kind: ClusterRole
  name: fortigate-ctrl
  apiGroup: rbac.authorization.k8s.io