apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote2-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote2-back
  template:
    metadata:
      labels:
        app: azure-vote2-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote2-back
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote2-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote2-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote2-front
spec:
  replicas: 5
  selector:
    matchLabels:
      app: azure-vote2-front
  template:
    metadata:
      labels:
        app: azure-vote2-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote2-front
        image: microsoft/azure-vote-front:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 156Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote2-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote2-front
  labels:
    app: azure-vote2-front
  annotations:
    lb-fgts.fortigates.fortinet.com/port: "90"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  # may try nodeport type to see if works better for K8S connector
  ports:
  - port: 80
  selector:
    app: azure-vote2-front
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-vote2-back-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-vote2-back
  targetCPUUtilizationPercentage: 50 # target CPU utilization


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-vote2-front-hpa
spec:
  maxReplicas: 40
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-vote2-front
  targetCPUUtilizationPercentage: 60 # target CPU utilization